services:
  solix:
    image: ghcr.io/denherrring/solixevreport:latest
    # build: .   # lokal bauen statt Image pullen
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
